name:                aoc17
version:             0.1.0.0
github:              d-dorazio/aoc17
license:             BSD3
author:              d-dorazio
maintainer:          d.dorazio96@gmail.com
copyright:           MIT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Advent of Code 2017
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/d-dorazio/aoc17#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hashtables
- megaparsec
- primitive
- text
- vector

ghc-options:
- -Wall
- -fwarn-tabs

library:
  source-dirs: src

executables:
  aoc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17
    - optparse-applicative

tests:
  aoc17-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17
